// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GenericMessage.proto

package gb.xxy.hr;

public final class GenericMessage {
  private GenericMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface GenericMessageNotificationOrBuilder extends
      // @@protoc_insertion_point(interface_extends:HU.GenericMessageNotification)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string message_id = 1;</code>
     */
    boolean hasMessageId();
    /**
     * <code>optional string message_id = 1;</code>
     */
    java.lang.String getMessageId();
    /**
     * <code>optional string message_id = 1;</code>
     */
    com.google.protobuf.ByteString
        getMessageIdBytes();

    /**
     * <code>optional string message_boddy = 2;</code>
     */
    boolean hasMessageBoddy();
    /**
     * <code>optional string message_boddy = 2;</code>
     */
    java.lang.String getMessageBoddy();
    /**
     * <code>optional string message_boddy = 2;</code>
     */
    com.google.protobuf.ByteString
        getMessageBoddyBytes();

    /**
     * <code>optional bytes icon = 3;</code>
     */
    boolean hasIcon();
    /**
     * <code>optional bytes icon = 3;</code>
     */
    com.google.protobuf.ByteString getIcon();
  }
  /**
   * Protobuf type {@code HU.GenericMessageNotification}
   */
  public  static final class GenericMessageNotification extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:HU.GenericMessageNotification)
      GenericMessageNotificationOrBuilder {
    // Use GenericMessageNotification.newBuilder() to construct.
    private GenericMessageNotification(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GenericMessageNotification() {
      messageId_ = "";
      messageBoddy_ = "";
      icon_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private GenericMessageNotification(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              messageId_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              messageBoddy_ = bs;
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              icon_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return gb.xxy.hr.GenericMessage.internal_static_HU_GenericMessageNotification_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return gb.xxy.hr.GenericMessage.internal_static_HU_GenericMessageNotification_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              gb.xxy.hr.GenericMessage.GenericMessageNotification.class, gb.xxy.hr.GenericMessage.GenericMessageNotification.Builder.class);
    }

    private int bitField0_;
    public static final int MESSAGE_ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object messageId_;
    /**
     * <code>optional string message_id = 1;</code>
     */
    public boolean hasMessageId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string message_id = 1;</code>
     */
    public java.lang.String getMessageId() {
      java.lang.Object ref = messageId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          messageId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string message_id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getMessageIdBytes() {
      java.lang.Object ref = messageId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        messageId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MESSAGE_BODDY_FIELD_NUMBER = 2;
    private volatile java.lang.Object messageBoddy_;
    /**
     * <code>optional string message_boddy = 2;</code>
     */
    public boolean hasMessageBoddy() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string message_boddy = 2;</code>
     */
    public java.lang.String getMessageBoddy() {
      java.lang.Object ref = messageBoddy_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          messageBoddy_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string message_boddy = 2;</code>
     */
    public com.google.protobuf.ByteString
        getMessageBoddyBytes() {
      java.lang.Object ref = messageBoddy_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        messageBoddy_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ICON_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString icon_;
    /**
     * <code>optional bytes icon = 3;</code>
     */
    public boolean hasIcon() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional bytes icon = 3;</code>
     */
    public com.google.protobuf.ByteString getIcon() {
      return icon_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, messageId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, messageBoddy_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, icon_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, messageId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, messageBoddy_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, icon_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof gb.xxy.hr.GenericMessage.GenericMessageNotification)) {
        return super.equals(obj);
      }
      gb.xxy.hr.GenericMessage.GenericMessageNotification other = (gb.xxy.hr.GenericMessage.GenericMessageNotification) obj;

      boolean result = true;
      result = result && (hasMessageId() == other.hasMessageId());
      if (hasMessageId()) {
        result = result && getMessageId()
            .equals(other.getMessageId());
      }
      result = result && (hasMessageBoddy() == other.hasMessageBoddy());
      if (hasMessageBoddy()) {
        result = result && getMessageBoddy()
            .equals(other.getMessageBoddy());
      }
      result = result && (hasIcon() == other.hasIcon());
      if (hasIcon()) {
        result = result && getIcon()
            .equals(other.getIcon());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasMessageId()) {
        hash = (37 * hash) + MESSAGE_ID_FIELD_NUMBER;
        hash = (53 * hash) + getMessageId().hashCode();
      }
      if (hasMessageBoddy()) {
        hash = (37 * hash) + MESSAGE_BODDY_FIELD_NUMBER;
        hash = (53 * hash) + getMessageBoddy().hashCode();
      }
      if (hasIcon()) {
        hash = (37 * hash) + ICON_FIELD_NUMBER;
        hash = (53 * hash) + getIcon().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static gb.xxy.hr.GenericMessage.GenericMessageNotification parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static gb.xxy.hr.GenericMessage.GenericMessageNotification parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static gb.xxy.hr.GenericMessage.GenericMessageNotification parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static gb.xxy.hr.GenericMessage.GenericMessageNotification parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static gb.xxy.hr.GenericMessage.GenericMessageNotification parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static gb.xxy.hr.GenericMessage.GenericMessageNotification parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static gb.xxy.hr.GenericMessage.GenericMessageNotification parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static gb.xxy.hr.GenericMessage.GenericMessageNotification parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static gb.xxy.hr.GenericMessage.GenericMessageNotification parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static gb.xxy.hr.GenericMessage.GenericMessageNotification parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(gb.xxy.hr.GenericMessage.GenericMessageNotification prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code HU.GenericMessageNotification}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:HU.GenericMessageNotification)
        gb.xxy.hr.GenericMessage.GenericMessageNotificationOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return gb.xxy.hr.GenericMessage.internal_static_HU_GenericMessageNotification_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return gb.xxy.hr.GenericMessage.internal_static_HU_GenericMessageNotification_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                gb.xxy.hr.GenericMessage.GenericMessageNotification.class, gb.xxy.hr.GenericMessage.GenericMessageNotification.Builder.class);
      }

      // Construct using gb.xxy.hr.GenericMessage.GenericMessageNotification.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        messageId_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        messageBoddy_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        icon_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return gb.xxy.hr.GenericMessage.internal_static_HU_GenericMessageNotification_descriptor;
      }

      public gb.xxy.hr.GenericMessage.GenericMessageNotification getDefaultInstanceForType() {
        return gb.xxy.hr.GenericMessage.GenericMessageNotification.getDefaultInstance();
      }

      public gb.xxy.hr.GenericMessage.GenericMessageNotification build() {
        gb.xxy.hr.GenericMessage.GenericMessageNotification result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public gb.xxy.hr.GenericMessage.GenericMessageNotification buildPartial() {
        gb.xxy.hr.GenericMessage.GenericMessageNotification result = new gb.xxy.hr.GenericMessage.GenericMessageNotification(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.messageId_ = messageId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.messageBoddy_ = messageBoddy_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.icon_ = icon_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof gb.xxy.hr.GenericMessage.GenericMessageNotification) {
          return mergeFrom((gb.xxy.hr.GenericMessage.GenericMessageNotification)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(gb.xxy.hr.GenericMessage.GenericMessageNotification other) {
        if (other == gb.xxy.hr.GenericMessage.GenericMessageNotification.getDefaultInstance()) return this;
        if (other.hasMessageId()) {
          bitField0_ |= 0x00000001;
          messageId_ = other.messageId_;
          onChanged();
        }
        if (other.hasMessageBoddy()) {
          bitField0_ |= 0x00000002;
          messageBoddy_ = other.messageBoddy_;
          onChanged();
        }
        if (other.hasIcon()) {
          setIcon(other.getIcon());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        gb.xxy.hr.GenericMessage.GenericMessageNotification parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (gb.xxy.hr.GenericMessage.GenericMessageNotification) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object messageId_ = "";
      /**
       * <code>optional string message_id = 1;</code>
       */
      public boolean hasMessageId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string message_id = 1;</code>
       */
      public java.lang.String getMessageId() {
        java.lang.Object ref = messageId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            messageId_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string message_id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getMessageIdBytes() {
        java.lang.Object ref = messageId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          messageId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string message_id = 1;</code>
       */
      public Builder setMessageId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        messageId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string message_id = 1;</code>
       */
      public Builder clearMessageId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        messageId_ = getDefaultInstance().getMessageId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string message_id = 1;</code>
       */
      public Builder setMessageIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        messageId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object messageBoddy_ = "";
      /**
       * <code>optional string message_boddy = 2;</code>
       */
      public boolean hasMessageBoddy() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string message_boddy = 2;</code>
       */
      public java.lang.String getMessageBoddy() {
        java.lang.Object ref = messageBoddy_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            messageBoddy_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string message_boddy = 2;</code>
       */
      public com.google.protobuf.ByteString
          getMessageBoddyBytes() {
        java.lang.Object ref = messageBoddy_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          messageBoddy_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string message_boddy = 2;</code>
       */
      public Builder setMessageBoddy(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        messageBoddy_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string message_boddy = 2;</code>
       */
      public Builder clearMessageBoddy() {
        bitField0_ = (bitField0_ & ~0x00000002);
        messageBoddy_ = getDefaultInstance().getMessageBoddy();
        onChanged();
        return this;
      }
      /**
       * <code>optional string message_boddy = 2;</code>
       */
      public Builder setMessageBoddyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        messageBoddy_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString icon_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes icon = 3;</code>
       */
      public boolean hasIcon() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional bytes icon = 3;</code>
       */
      public com.google.protobuf.ByteString getIcon() {
        return icon_;
      }
      /**
       * <code>optional bytes icon = 3;</code>
       */
      public Builder setIcon(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        icon_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes icon = 3;</code>
       */
      public Builder clearIcon() {
        bitField0_ = (bitField0_ & ~0x00000004);
        icon_ = getDefaultInstance().getIcon();
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:HU.GenericMessageNotification)
    }

    // @@protoc_insertion_point(class_scope:HU.GenericMessageNotification)
    private static final gb.xxy.hr.GenericMessage.GenericMessageNotification DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new gb.xxy.hr.GenericMessage.GenericMessageNotification();
    }

    public static gb.xxy.hr.GenericMessage.GenericMessageNotification getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<GenericMessageNotification>
        PARSER = new com.google.protobuf.AbstractParser<GenericMessageNotification>() {
      public GenericMessageNotification parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new GenericMessageNotification(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GenericMessageNotification> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GenericMessageNotification> getParserForType() {
      return PARSER;
    }

    public gb.xxy.hr.GenericMessage.GenericMessageNotification getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_HU_GenericMessageNotification_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_HU_GenericMessageNotification_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024GenericMessage.proto\022\002HU\"U\n\032GenericMes" +
      "sageNotification\022\022\n\nmessage_id\030\001 \001(\t\022\025\n\r" +
      "message_boddy\030\002 \001(\t\022\014\n\004icon\030\003 \001(\014B\033\n\tgb." +
      "xxy.hrB\016GenericMessage"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_HU_GenericMessageNotification_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_HU_GenericMessageNotification_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_HU_GenericMessageNotification_descriptor,
        new java.lang.String[] { "MessageId", "MessageBoddy", "Icon", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
