// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: location.proto

package gb.xxy.hr;

public final class LocationProtos {
  private LocationProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface LocationDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:gb.xxy.hr.LocationData)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional uint64 timestamp = 1;</code>
     */
    boolean hasTimestamp();
    /**
     * <code>optional uint64 timestamp = 1;</code>
     */
    long getTimestamp();

    /**
     * <code>optional int32 latitude = 2;</code>
     */
    boolean hasLatitude();
    /**
     * <code>optional int32 latitude = 2;</code>
     */
    int getLatitude();

    /**
     * <code>optional int32 longitude = 3;</code>
     */
    boolean hasLongitude();
    /**
     * <code>optional int32 longitude = 3;</code>
     */
    int getLongitude();

    /**
     * <code>optional uint32 accuracy = 4;</code>
     */
    boolean hasAccuracy();
    /**
     * <code>optional uint32 accuracy = 4;</code>
     */
    int getAccuracy();

    /**
     * <code>optional int32 altitude = 5;</code>
     */
    boolean hasAltitude();
    /**
     * <code>optional int32 altitude = 5;</code>
     */
    int getAltitude();

    /**
     * <code>optional int32 speed = 6;</code>
     */
    boolean hasSpeed();
    /**
     * <code>optional int32 speed = 6;</code>
     */
    int getSpeed();

    /**
     * <code>optional int32 bearing = 7;</code>
     */
    boolean hasBearing();
    /**
     * <code>optional int32 bearing = 7;</code>
     */
    int getBearing();
  }
  /**
   * Protobuf type {@code gb.xxy.hr.LocationData}
   */
  public  static final class LocationData extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:gb.xxy.hr.LocationData)
      LocationDataOrBuilder {
    // Use LocationData.newBuilder() to construct.
    private LocationData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private LocationData() {
      timestamp_ = 0L;
      latitude_ = 0;
      longitude_ = 0;
      accuracy_ = 0;
      altitude_ = 0;
      speed_ = 0;
      bearing_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private LocationData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              timestamp_ = input.readUInt64();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              latitude_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              longitude_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              accuracy_ = input.readUInt32();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              altitude_ = input.readInt32();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              speed_ = input.readInt32();
              break;
            }
            case 56: {
              bitField0_ |= 0x00000040;
              bearing_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return gb.xxy.hr.LocationProtos.internal_static_gb_xxy_hr_LocationData_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return gb.xxy.hr.LocationProtos.internal_static_gb_xxy_hr_LocationData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              gb.xxy.hr.LocationProtos.LocationData.class, gb.xxy.hr.LocationProtos.LocationData.Builder.class);
    }

    private int bitField0_;
    public static final int TIMESTAMP_FIELD_NUMBER = 1;
    private long timestamp_;
    /**
     * <code>optional uint64 timestamp = 1;</code>
     */
    public boolean hasTimestamp() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional uint64 timestamp = 1;</code>
     */
    public long getTimestamp() {
      return timestamp_;
    }

    public static final int LATITUDE_FIELD_NUMBER = 2;
    private int latitude_;
    /**
     * <code>optional int32 latitude = 2;</code>
     */
    public boolean hasLatitude() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 latitude = 2;</code>
     */
    public int getLatitude() {
      return latitude_;
    }

    public static final int LONGITUDE_FIELD_NUMBER = 3;
    private int longitude_;
    /**
     * <code>optional int32 longitude = 3;</code>
     */
    public boolean hasLongitude() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int32 longitude = 3;</code>
     */
    public int getLongitude() {
      return longitude_;
    }

    public static final int ACCURACY_FIELD_NUMBER = 4;
    private int accuracy_;
    /**
     * <code>optional uint32 accuracy = 4;</code>
     */
    public boolean hasAccuracy() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional uint32 accuracy = 4;</code>
     */
    public int getAccuracy() {
      return accuracy_;
    }

    public static final int ALTITUDE_FIELD_NUMBER = 5;
    private int altitude_;
    /**
     * <code>optional int32 altitude = 5;</code>
     */
    public boolean hasAltitude() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional int32 altitude = 5;</code>
     */
    public int getAltitude() {
      return altitude_;
    }

    public static final int SPEED_FIELD_NUMBER = 6;
    private int speed_;
    /**
     * <code>optional int32 speed = 6;</code>
     */
    public boolean hasSpeed() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional int32 speed = 6;</code>
     */
    public int getSpeed() {
      return speed_;
    }

    public static final int BEARING_FIELD_NUMBER = 7;
    private int bearing_;
    /**
     * <code>optional int32 bearing = 7;</code>
     */
    public boolean hasBearing() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional int32 bearing = 7;</code>
     */
    public int getBearing() {
      return bearing_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt64(1, timestamp_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, latitude_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, longitude_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeUInt32(4, accuracy_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(5, altitude_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeInt32(6, speed_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeInt32(7, bearing_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, timestamp_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, latitude_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, longitude_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(4, accuracy_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, altitude_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, speed_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, bearing_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof gb.xxy.hr.LocationProtos.LocationData)) {
        return super.equals(obj);
      }
      gb.xxy.hr.LocationProtos.LocationData other = (gb.xxy.hr.LocationProtos.LocationData) obj;

      boolean result = true;
      result = result && (hasTimestamp() == other.hasTimestamp());
      if (hasTimestamp()) {
        result = result && (getTimestamp()
            == other.getTimestamp());
      }
      result = result && (hasLatitude() == other.hasLatitude());
      if (hasLatitude()) {
        result = result && (getLatitude()
            == other.getLatitude());
      }
      result = result && (hasLongitude() == other.hasLongitude());
      if (hasLongitude()) {
        result = result && (getLongitude()
            == other.getLongitude());
      }
      result = result && (hasAccuracy() == other.hasAccuracy());
      if (hasAccuracy()) {
        result = result && (getAccuracy()
            == other.getAccuracy());
      }
      result = result && (hasAltitude() == other.hasAltitude());
      if (hasAltitude()) {
        result = result && (getAltitude()
            == other.getAltitude());
      }
      result = result && (hasSpeed() == other.hasSpeed());
      if (hasSpeed()) {
        result = result && (getSpeed()
            == other.getSpeed());
      }
      result = result && (hasBearing() == other.hasBearing());
      if (hasBearing()) {
        result = result && (getBearing()
            == other.getBearing());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasTimestamp()) {
        hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getTimestamp());
      }
      if (hasLatitude()) {
        hash = (37 * hash) + LATITUDE_FIELD_NUMBER;
        hash = (53 * hash) + getLatitude();
      }
      if (hasLongitude()) {
        hash = (37 * hash) + LONGITUDE_FIELD_NUMBER;
        hash = (53 * hash) + getLongitude();
      }
      if (hasAccuracy()) {
        hash = (37 * hash) + ACCURACY_FIELD_NUMBER;
        hash = (53 * hash) + getAccuracy();
      }
      if (hasAltitude()) {
        hash = (37 * hash) + ALTITUDE_FIELD_NUMBER;
        hash = (53 * hash) + getAltitude();
      }
      if (hasSpeed()) {
        hash = (37 * hash) + SPEED_FIELD_NUMBER;
        hash = (53 * hash) + getSpeed();
      }
      if (hasBearing()) {
        hash = (37 * hash) + BEARING_FIELD_NUMBER;
        hash = (53 * hash) + getBearing();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static gb.xxy.hr.LocationProtos.LocationData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static gb.xxy.hr.LocationProtos.LocationData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static gb.xxy.hr.LocationProtos.LocationData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static gb.xxy.hr.LocationProtos.LocationData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static gb.xxy.hr.LocationProtos.LocationData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static gb.xxy.hr.LocationProtos.LocationData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static gb.xxy.hr.LocationProtos.LocationData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static gb.xxy.hr.LocationProtos.LocationData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static gb.xxy.hr.LocationProtos.LocationData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static gb.xxy.hr.LocationProtos.LocationData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(gb.xxy.hr.LocationProtos.LocationData prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code gb.xxy.hr.LocationData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:gb.xxy.hr.LocationData)
        gb.xxy.hr.LocationProtos.LocationDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return gb.xxy.hr.LocationProtos.internal_static_gb_xxy_hr_LocationData_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return gb.xxy.hr.LocationProtos.internal_static_gb_xxy_hr_LocationData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                gb.xxy.hr.LocationProtos.LocationData.class, gb.xxy.hr.LocationProtos.LocationData.Builder.class);
      }

      // Construct using gb.xxy.hr.LocationProtos.LocationData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        timestamp_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        latitude_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        longitude_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        accuracy_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        altitude_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        speed_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        bearing_ = 0;
        bitField0_ = (bitField0_ & ~0x00000040);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return gb.xxy.hr.LocationProtos.internal_static_gb_xxy_hr_LocationData_descriptor;
      }

      public gb.xxy.hr.LocationProtos.LocationData getDefaultInstanceForType() {
        return gb.xxy.hr.LocationProtos.LocationData.getDefaultInstance();
      }

      public gb.xxy.hr.LocationProtos.LocationData build() {
        gb.xxy.hr.LocationProtos.LocationData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public gb.xxy.hr.LocationProtos.LocationData buildPartial() {
        gb.xxy.hr.LocationProtos.LocationData result = new gb.xxy.hr.LocationProtos.LocationData(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.timestamp_ = timestamp_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.latitude_ = latitude_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.longitude_ = longitude_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.accuracy_ = accuracy_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.altitude_ = altitude_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.speed_ = speed_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.bearing_ = bearing_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof gb.xxy.hr.LocationProtos.LocationData) {
          return mergeFrom((gb.xxy.hr.LocationProtos.LocationData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(gb.xxy.hr.LocationProtos.LocationData other) {
        if (other == gb.xxy.hr.LocationProtos.LocationData.getDefaultInstance()) return this;
        if (other.hasTimestamp()) {
          setTimestamp(other.getTimestamp());
        }
        if (other.hasLatitude()) {
          setLatitude(other.getLatitude());
        }
        if (other.hasLongitude()) {
          setLongitude(other.getLongitude());
        }
        if (other.hasAccuracy()) {
          setAccuracy(other.getAccuracy());
        }
        if (other.hasAltitude()) {
          setAltitude(other.getAltitude());
        }
        if (other.hasSpeed()) {
          setSpeed(other.getSpeed());
        }
        if (other.hasBearing()) {
          setBearing(other.getBearing());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        gb.xxy.hr.LocationProtos.LocationData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (gb.xxy.hr.LocationProtos.LocationData) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long timestamp_ ;
      /**
       * <code>optional uint64 timestamp = 1;</code>
       */
      public boolean hasTimestamp() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional uint64 timestamp = 1;</code>
       */
      public long getTimestamp() {
        return timestamp_;
      }
      /**
       * <code>optional uint64 timestamp = 1;</code>
       */
      public Builder setTimestamp(long value) {
        bitField0_ |= 0x00000001;
        timestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 timestamp = 1;</code>
       */
      public Builder clearTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000001);
        timestamp_ = 0L;
        onChanged();
        return this;
      }

      private int latitude_ ;
      /**
       * <code>optional int32 latitude = 2;</code>
       */
      public boolean hasLatitude() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 latitude = 2;</code>
       */
      public int getLatitude() {
        return latitude_;
      }
      /**
       * <code>optional int32 latitude = 2;</code>
       */
      public Builder setLatitude(int value) {
        bitField0_ |= 0x00000002;
        latitude_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 latitude = 2;</code>
       */
      public Builder clearLatitude() {
        bitField0_ = (bitField0_ & ~0x00000002);
        latitude_ = 0;
        onChanged();
        return this;
      }

      private int longitude_ ;
      /**
       * <code>optional int32 longitude = 3;</code>
       */
      public boolean hasLongitude() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int32 longitude = 3;</code>
       */
      public int getLongitude() {
        return longitude_;
      }
      /**
       * <code>optional int32 longitude = 3;</code>
       */
      public Builder setLongitude(int value) {
        bitField0_ |= 0x00000004;
        longitude_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 longitude = 3;</code>
       */
      public Builder clearLongitude() {
        bitField0_ = (bitField0_ & ~0x00000004);
        longitude_ = 0;
        onChanged();
        return this;
      }

      private int accuracy_ ;
      /**
       * <code>optional uint32 accuracy = 4;</code>
       */
      public boolean hasAccuracy() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional uint32 accuracy = 4;</code>
       */
      public int getAccuracy() {
        return accuracy_;
      }
      /**
       * <code>optional uint32 accuracy = 4;</code>
       */
      public Builder setAccuracy(int value) {
        bitField0_ |= 0x00000008;
        accuracy_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 accuracy = 4;</code>
       */
      public Builder clearAccuracy() {
        bitField0_ = (bitField0_ & ~0x00000008);
        accuracy_ = 0;
        onChanged();
        return this;
      }

      private int altitude_ ;
      /**
       * <code>optional int32 altitude = 5;</code>
       */
      public boolean hasAltitude() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional int32 altitude = 5;</code>
       */
      public int getAltitude() {
        return altitude_;
      }
      /**
       * <code>optional int32 altitude = 5;</code>
       */
      public Builder setAltitude(int value) {
        bitField0_ |= 0x00000010;
        altitude_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 altitude = 5;</code>
       */
      public Builder clearAltitude() {
        bitField0_ = (bitField0_ & ~0x00000010);
        altitude_ = 0;
        onChanged();
        return this;
      }

      private int speed_ ;
      /**
       * <code>optional int32 speed = 6;</code>
       */
      public boolean hasSpeed() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional int32 speed = 6;</code>
       */
      public int getSpeed() {
        return speed_;
      }
      /**
       * <code>optional int32 speed = 6;</code>
       */
      public Builder setSpeed(int value) {
        bitField0_ |= 0x00000020;
        speed_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 speed = 6;</code>
       */
      public Builder clearSpeed() {
        bitField0_ = (bitField0_ & ~0x00000020);
        speed_ = 0;
        onChanged();
        return this;
      }

      private int bearing_ ;
      /**
       * <code>optional int32 bearing = 7;</code>
       */
      public boolean hasBearing() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional int32 bearing = 7;</code>
       */
      public int getBearing() {
        return bearing_;
      }
      /**
       * <code>optional int32 bearing = 7;</code>
       */
      public Builder setBearing(int value) {
        bitField0_ |= 0x00000040;
        bearing_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 bearing = 7;</code>
       */
      public Builder clearBearing() {
        bitField0_ = (bitField0_ & ~0x00000040);
        bearing_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:gb.xxy.hr.LocationData)
    }

    // @@protoc_insertion_point(class_scope:gb.xxy.hr.LocationData)
    private static final gb.xxy.hr.LocationProtos.LocationData DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new gb.xxy.hr.LocationProtos.LocationData();
    }

    public static gb.xxy.hr.LocationProtos.LocationData getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<LocationData>
        PARSER = new com.google.protobuf.AbstractParser<LocationData>() {
      public LocationData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new LocationData(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<LocationData> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<LocationData> getParserForType() {
      return PARSER;
    }

    public gb.xxy.hr.LocationProtos.LocationData getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_gb_xxy_hr_LocationData_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_gb_xxy_hr_LocationData_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016location.proto\022\tgb.xxy.hr\"\212\001\n\014Location" +
      "Data\022\021\n\ttimestamp\030\001 \001(\004\022\020\n\010latitude\030\002 \001(" +
      "\005\022\021\n\tlongitude\030\003 \001(\005\022\020\n\010accuracy\030\004 \001(\r\022\020" +
      "\n\010altitude\030\005 \001(\005\022\r\n\005speed\030\006 \001(\005\022\017\n\007beari" +
      "ng\030\007 \001(\005B\033\n\tgb.xxy.hrB\016LocationProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_gb_xxy_hr_LocationData_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_gb_xxy_hr_LocationData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_gb_xxy_hr_LocationData_descriptor,
        new java.lang.String[] { "Timestamp", "Latitude", "Longitude", "Accuracy", "Altitude", "Speed", "Bearing", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
