// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: media.proto

package gb.xxy.hr;

public final class MediaServices {
  private MediaServices() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code HU.MediaStatus}
   */
  public enum MediaStatus
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>MSG_TYPE_SENSORSTARTREQUEST = 32769;</code>
     */
    MSG_TYPE_SENSORSTARTREQUEST(32769),
    /**
     * <code>MSG_TYPE_SENSORSTARTRESPONSE = 32770;</code>
     */
    MSG_TYPE_SENSORSTARTRESPONSE(32770),
    /**
     * <code>MSG_TYPE_SENSOREVENT = 32771;</code>
     */
    MSG_TYPE_SENSOREVENT(32771),
    ;

    /**
     * <code>MSG_TYPE_SENSORSTARTREQUEST = 32769;</code>
     */
    public static final int MSG_TYPE_SENSORSTARTREQUEST_VALUE = 32769;
    /**
     * <code>MSG_TYPE_SENSORSTARTRESPONSE = 32770;</code>
     */
    public static final int MSG_TYPE_SENSORSTARTRESPONSE_VALUE = 32770;
    /**
     * <code>MSG_TYPE_SENSOREVENT = 32771;</code>
     */
    public static final int MSG_TYPE_SENSOREVENT_VALUE = 32771;


    public final int getNumber() {
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static MediaStatus valueOf(int value) {
      return forNumber(value);
    }

    public static MediaStatus forNumber(int value) {
      switch (value) {
        case 32769: return MSG_TYPE_SENSORSTARTREQUEST;
        case 32770: return MSG_TYPE_SENSORSTARTRESPONSE;
        case 32771: return MSG_TYPE_SENSOREVENT;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<MediaStatus>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        MediaStatus> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<MediaStatus>() {
            public MediaStatus findValueByNumber(int number) {
              return MediaStatus.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return gb.xxy.hr.MediaServices.getDescriptor().getEnumTypes().get(0);
    }

    private static final MediaStatus[] VALUES = values();

    public static MediaStatus valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private MediaStatus(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:HU.MediaStatus)
  }

  public interface MediaServiceOrBuilder extends
      // @@protoc_insertion_point(interface_extends:HU.MediaService)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .HU.MediaService.MedStat state = 1;</code>
     */
    boolean hasState();
    /**
     * <code>optional .HU.MediaService.MedStat state = 1;</code>
     */
    gb.xxy.hr.MediaServices.MediaService.MedStat getState();

    /**
     * <code>optional string source = 2;</code>
     */
    boolean hasSource();
    /**
     * <code>optional string source = 2;</code>
     */
    java.lang.String getSource();
    /**
     * <code>optional string source = 2;</code>
     */
    com.google.protobuf.ByteString
        getSourceBytes();

    /**
     * <code>optional uint32 seconds = 3;</code>
     */
    boolean hasSeconds();
    /**
     * <code>optional uint32 seconds = 3;</code>
     */
    int getSeconds();

    /**
     * <code>optional bool shuffle = 4;</code>
     */
    boolean hasShuffle();
    /**
     * <code>optional bool shuffle = 4;</code>
     */
    boolean getShuffle();

    /**
     * <code>optional bool repeat = 5;</code>
     */
    boolean hasRepeat();
    /**
     * <code>optional bool repeat = 5;</code>
     */
    boolean getRepeat();

    /**
     * <code>optional bool repeat_one = 6;</code>
     */
    boolean hasRepeatOne();
    /**
     * <code>optional bool repeat_one = 6;</code>
     */
    boolean getRepeatOne();
  }
  /**
   * Protobuf type {@code HU.MediaService}
   */
  public  static final class MediaService extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:HU.MediaService)
      MediaServiceOrBuilder {
    // Use MediaService.newBuilder() to construct.
    private MediaService(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MediaService() {
      state_ = 0;
      source_ = "";
      seconds_ = 0;
      shuffle_ = false;
      repeat_ = false;
      repeatOne_ = false;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MediaService(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              gb.xxy.hr.MediaServices.MediaService.MedStat value = gb.xxy.hr.MediaServices.MediaService.MedStat.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                state_ = rawValue;
              }
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              source_ = bs;
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              seconds_ = input.readUInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              shuffle_ = input.readBool();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              repeat_ = input.readBool();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              repeatOne_ = input.readBool();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return gb.xxy.hr.MediaServices.internal_static_HU_MediaService_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return gb.xxy.hr.MediaServices.internal_static_HU_MediaService_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              gb.xxy.hr.MediaServices.MediaService.class, gb.xxy.hr.MediaServices.MediaService.Builder.class);
    }

    /**
     * Protobuf enum {@code HU.MediaService.MedStat}
     */
    public enum MedStat
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>PAUSE = 0;</code>
       */
      PAUSE(0),
      /**
       * <code>STOPPED = 1;</code>
       */
      STOPPED(1),
      /**
       * <code>PLAYING = 3;</code>
       */
      PLAYING(3),
      ;

      /**
       * <code>PAUSE = 0;</code>
       */
      public static final int PAUSE_VALUE = 0;
      /**
       * <code>STOPPED = 1;</code>
       */
      public static final int STOPPED_VALUE = 1;
      /**
       * <code>PLAYING = 3;</code>
       */
      public static final int PLAYING_VALUE = 3;


      public final int getNumber() {
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static MedStat valueOf(int value) {
        return forNumber(value);
      }

      public static MedStat forNumber(int value) {
        switch (value) {
          case 0: return PAUSE;
          case 1: return STOPPED;
          case 3: return PLAYING;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<MedStat>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          MedStat> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<MedStat>() {
              public MedStat findValueByNumber(int number) {
                return MedStat.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return gb.xxy.hr.MediaServices.MediaService.getDescriptor().getEnumTypes().get(0);
      }

      private static final MedStat[] VALUES = values();

      public static MedStat valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private MedStat(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:HU.MediaService.MedStat)
    }

    private int bitField0_;
    public static final int STATE_FIELD_NUMBER = 1;
    private int state_;
    /**
     * <code>optional .HU.MediaService.MedStat state = 1;</code>
     */
    public boolean hasState() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .HU.MediaService.MedStat state = 1;</code>
     */
    public gb.xxy.hr.MediaServices.MediaService.MedStat getState() {
      gb.xxy.hr.MediaServices.MediaService.MedStat result = gb.xxy.hr.MediaServices.MediaService.MedStat.valueOf(state_);
      return result == null ? gb.xxy.hr.MediaServices.MediaService.MedStat.PAUSE : result;
    }

    public static final int SOURCE_FIELD_NUMBER = 2;
    private volatile java.lang.Object source_;
    /**
     * <code>optional string source = 2;</code>
     */
    public boolean hasSource() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string source = 2;</code>
     */
    public java.lang.String getSource() {
      java.lang.Object ref = source_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          source_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string source = 2;</code>
     */
    public com.google.protobuf.ByteString
        getSourceBytes() {
      java.lang.Object ref = source_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        source_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SECONDS_FIELD_NUMBER = 3;
    private int seconds_;
    /**
     * <code>optional uint32 seconds = 3;</code>
     */
    public boolean hasSeconds() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional uint32 seconds = 3;</code>
     */
    public int getSeconds() {
      return seconds_;
    }

    public static final int SHUFFLE_FIELD_NUMBER = 4;
    private boolean shuffle_;
    /**
     * <code>optional bool shuffle = 4;</code>
     */
    public boolean hasShuffle() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional bool shuffle = 4;</code>
     */
    public boolean getShuffle() {
      return shuffle_;
    }

    public static final int REPEAT_FIELD_NUMBER = 5;
    private boolean repeat_;
    /**
     * <code>optional bool repeat = 5;</code>
     */
    public boolean hasRepeat() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional bool repeat = 5;</code>
     */
    public boolean getRepeat() {
      return repeat_;
    }

    public static final int REPEAT_ONE_FIELD_NUMBER = 6;
    private boolean repeatOne_;
    /**
     * <code>optional bool repeat_one = 6;</code>
     */
    public boolean hasRepeatOne() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional bool repeat_one = 6;</code>
     */
    public boolean getRepeatOne() {
      return repeatOne_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, state_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, source_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeUInt32(3, seconds_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBool(4, shuffle_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBool(5, repeat_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBool(6, repeatOne_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, state_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, source_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(3, seconds_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(4, shuffle_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(5, repeat_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(6, repeatOne_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof gb.xxy.hr.MediaServices.MediaService)) {
        return super.equals(obj);
      }
      gb.xxy.hr.MediaServices.MediaService other = (gb.xxy.hr.MediaServices.MediaService) obj;

      boolean result = true;
      result = result && (hasState() == other.hasState());
      if (hasState()) {
        result = result && state_ == other.state_;
      }
      result = result && (hasSource() == other.hasSource());
      if (hasSource()) {
        result = result && getSource()
            .equals(other.getSource());
      }
      result = result && (hasSeconds() == other.hasSeconds());
      if (hasSeconds()) {
        result = result && (getSeconds()
            == other.getSeconds());
      }
      result = result && (hasShuffle() == other.hasShuffle());
      if (hasShuffle()) {
        result = result && (getShuffle()
            == other.getShuffle());
      }
      result = result && (hasRepeat() == other.hasRepeat());
      if (hasRepeat()) {
        result = result && (getRepeat()
            == other.getRepeat());
      }
      result = result && (hasRepeatOne() == other.hasRepeatOne());
      if (hasRepeatOne()) {
        result = result && (getRepeatOne()
            == other.getRepeatOne());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasState()) {
        hash = (37 * hash) + STATE_FIELD_NUMBER;
        hash = (53 * hash) + state_;
      }
      if (hasSource()) {
        hash = (37 * hash) + SOURCE_FIELD_NUMBER;
        hash = (53 * hash) + getSource().hashCode();
      }
      if (hasSeconds()) {
        hash = (37 * hash) + SECONDS_FIELD_NUMBER;
        hash = (53 * hash) + getSeconds();
      }
      if (hasShuffle()) {
        hash = (37 * hash) + SHUFFLE_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getShuffle());
      }
      if (hasRepeat()) {
        hash = (37 * hash) + REPEAT_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getRepeat());
      }
      if (hasRepeatOne()) {
        hash = (37 * hash) + REPEAT_ONE_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getRepeatOne());
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static gb.xxy.hr.MediaServices.MediaService parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static gb.xxy.hr.MediaServices.MediaService parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static gb.xxy.hr.MediaServices.MediaService parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static gb.xxy.hr.MediaServices.MediaService parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static gb.xxy.hr.MediaServices.MediaService parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static gb.xxy.hr.MediaServices.MediaService parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static gb.xxy.hr.MediaServices.MediaService parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static gb.xxy.hr.MediaServices.MediaService parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static gb.xxy.hr.MediaServices.MediaService parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static gb.xxy.hr.MediaServices.MediaService parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(gb.xxy.hr.MediaServices.MediaService prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code HU.MediaService}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:HU.MediaService)
        gb.xxy.hr.MediaServices.MediaServiceOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return gb.xxy.hr.MediaServices.internal_static_HU_MediaService_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return gb.xxy.hr.MediaServices.internal_static_HU_MediaService_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                gb.xxy.hr.MediaServices.MediaService.class, gb.xxy.hr.MediaServices.MediaService.Builder.class);
      }

      // Construct using gb.xxy.hr.MediaServices.MediaService.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        state_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        source_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        seconds_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        shuffle_ = false;
        bitField0_ = (bitField0_ & ~0x00000008);
        repeat_ = false;
        bitField0_ = (bitField0_ & ~0x00000010);
        repeatOne_ = false;
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return gb.xxy.hr.MediaServices.internal_static_HU_MediaService_descriptor;
      }

      public gb.xxy.hr.MediaServices.MediaService getDefaultInstanceForType() {
        return gb.xxy.hr.MediaServices.MediaService.getDefaultInstance();
      }

      public gb.xxy.hr.MediaServices.MediaService build() {
        gb.xxy.hr.MediaServices.MediaService result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public gb.xxy.hr.MediaServices.MediaService buildPartial() {
        gb.xxy.hr.MediaServices.MediaService result = new gb.xxy.hr.MediaServices.MediaService(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.state_ = state_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.source_ = source_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.seconds_ = seconds_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.shuffle_ = shuffle_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.repeat_ = repeat_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.repeatOne_ = repeatOne_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof gb.xxy.hr.MediaServices.MediaService) {
          return mergeFrom((gb.xxy.hr.MediaServices.MediaService)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(gb.xxy.hr.MediaServices.MediaService other) {
        if (other == gb.xxy.hr.MediaServices.MediaService.getDefaultInstance()) return this;
        if (other.hasState()) {
          setState(other.getState());
        }
        if (other.hasSource()) {
          bitField0_ |= 0x00000002;
          source_ = other.source_;
          onChanged();
        }
        if (other.hasSeconds()) {
          setSeconds(other.getSeconds());
        }
        if (other.hasShuffle()) {
          setShuffle(other.getShuffle());
        }
        if (other.hasRepeat()) {
          setRepeat(other.getRepeat());
        }
        if (other.hasRepeatOne()) {
          setRepeatOne(other.getRepeatOne());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        gb.xxy.hr.MediaServices.MediaService parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (gb.xxy.hr.MediaServices.MediaService) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int state_ = 0;
      /**
       * <code>optional .HU.MediaService.MedStat state = 1;</code>
       */
      public boolean hasState() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .HU.MediaService.MedStat state = 1;</code>
       */
      public gb.xxy.hr.MediaServices.MediaService.MedStat getState() {
        gb.xxy.hr.MediaServices.MediaService.MedStat result = gb.xxy.hr.MediaServices.MediaService.MedStat.valueOf(state_);
        return result == null ? gb.xxy.hr.MediaServices.MediaService.MedStat.PAUSE : result;
      }
      /**
       * <code>optional .HU.MediaService.MedStat state = 1;</code>
       */
      public Builder setState(gb.xxy.hr.MediaServices.MediaService.MedStat value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        state_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional .HU.MediaService.MedStat state = 1;</code>
       */
      public Builder clearState() {
        bitField0_ = (bitField0_ & ~0x00000001);
        state_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object source_ = "";
      /**
       * <code>optional string source = 2;</code>
       */
      public boolean hasSource() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string source = 2;</code>
       */
      public java.lang.String getSource() {
        java.lang.Object ref = source_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            source_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string source = 2;</code>
       */
      public com.google.protobuf.ByteString
          getSourceBytes() {
        java.lang.Object ref = source_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          source_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string source = 2;</code>
       */
      public Builder setSource(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        source_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string source = 2;</code>
       */
      public Builder clearSource() {
        bitField0_ = (bitField0_ & ~0x00000002);
        source_ = getDefaultInstance().getSource();
        onChanged();
        return this;
      }
      /**
       * <code>optional string source = 2;</code>
       */
      public Builder setSourceBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        source_ = value;
        onChanged();
        return this;
      }

      private int seconds_ ;
      /**
       * <code>optional uint32 seconds = 3;</code>
       */
      public boolean hasSeconds() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional uint32 seconds = 3;</code>
       */
      public int getSeconds() {
        return seconds_;
      }
      /**
       * <code>optional uint32 seconds = 3;</code>
       */
      public Builder setSeconds(int value) {
        bitField0_ |= 0x00000004;
        seconds_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 seconds = 3;</code>
       */
      public Builder clearSeconds() {
        bitField0_ = (bitField0_ & ~0x00000004);
        seconds_ = 0;
        onChanged();
        return this;
      }

      private boolean shuffle_ ;
      /**
       * <code>optional bool shuffle = 4;</code>
       */
      public boolean hasShuffle() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional bool shuffle = 4;</code>
       */
      public boolean getShuffle() {
        return shuffle_;
      }
      /**
       * <code>optional bool shuffle = 4;</code>
       */
      public Builder setShuffle(boolean value) {
        bitField0_ |= 0x00000008;
        shuffle_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool shuffle = 4;</code>
       */
      public Builder clearShuffle() {
        bitField0_ = (bitField0_ & ~0x00000008);
        shuffle_ = false;
        onChanged();
        return this;
      }

      private boolean repeat_ ;
      /**
       * <code>optional bool repeat = 5;</code>
       */
      public boolean hasRepeat() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional bool repeat = 5;</code>
       */
      public boolean getRepeat() {
        return repeat_;
      }
      /**
       * <code>optional bool repeat = 5;</code>
       */
      public Builder setRepeat(boolean value) {
        bitField0_ |= 0x00000010;
        repeat_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool repeat = 5;</code>
       */
      public Builder clearRepeat() {
        bitField0_ = (bitField0_ & ~0x00000010);
        repeat_ = false;
        onChanged();
        return this;
      }

      private boolean repeatOne_ ;
      /**
       * <code>optional bool repeat_one = 6;</code>
       */
      public boolean hasRepeatOne() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional bool repeat_one = 6;</code>
       */
      public boolean getRepeatOne() {
        return repeatOne_;
      }
      /**
       * <code>optional bool repeat_one = 6;</code>
       */
      public Builder setRepeatOne(boolean value) {
        bitField0_ |= 0x00000020;
        repeatOne_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool repeat_one = 6;</code>
       */
      public Builder clearRepeatOne() {
        bitField0_ = (bitField0_ & ~0x00000020);
        repeatOne_ = false;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:HU.MediaService)
    }

    // @@protoc_insertion_point(class_scope:HU.MediaService)
    private static final gb.xxy.hr.MediaServices.MediaService DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new gb.xxy.hr.MediaServices.MediaService();
    }

    public static gb.xxy.hr.MediaServices.MediaService getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<MediaService>
        PARSER = new com.google.protobuf.AbstractParser<MediaService>() {
      public MediaService parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new MediaService(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MediaService> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MediaService> getParserForType() {
      return PARSER;
    }

    public gb.xxy.hr.MediaServices.MediaService getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface MediaMetaDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:HU.MediaMetaData)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string song = 1;</code>
     */
    boolean hasSong();
    /**
     * <code>optional string song = 1;</code>
     */
    java.lang.String getSong();
    /**
     * <code>optional string song = 1;</code>
     */
    com.google.protobuf.ByteString
        getSongBytes();

    /**
     * <code>optional string artist = 2;</code>
     */
    boolean hasArtist();
    /**
     * <code>optional string artist = 2;</code>
     */
    java.lang.String getArtist();
    /**
     * <code>optional string artist = 2;</code>
     */
    com.google.protobuf.ByteString
        getArtistBytes();

    /**
     * <code>optional string album = 3;</code>
     */
    boolean hasAlbum();
    /**
     * <code>optional string album = 3;</code>
     */
    java.lang.String getAlbum();
    /**
     * <code>optional string album = 3;</code>
     */
    com.google.protobuf.ByteString
        getAlbumBytes();

    /**
     * <code>optional bytes albumart = 4;</code>
     */
    boolean hasAlbumart();
    /**
     * <code>optional bytes albumart = 4;</code>
     */
    com.google.protobuf.ByteString getAlbumart();

    /**
     * <code>optional string playlist = 5;</code>
     */
    boolean hasPlaylist();
    /**
     * <code>optional string playlist = 5;</code>
     */
    java.lang.String getPlaylist();
    /**
     * <code>optional string playlist = 5;</code>
     */
    com.google.protobuf.ByteString
        getPlaylistBytes();

    /**
     * <code>optional uint32 duration = 6;</code>
     */
    boolean hasDuration();
    /**
     * <code>optional uint32 duration = 6;</code>
     */
    int getDuration();

    /**
     * <code>optional uint32 rating = 7;</code>
     */
    boolean hasRating();
    /**
     * <code>optional uint32 rating = 7;</code>
     */
    int getRating();
  }
  /**
   * Protobuf type {@code HU.MediaMetaData}
   */
  public  static final class MediaMetaData extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:HU.MediaMetaData)
      MediaMetaDataOrBuilder {
    // Use MediaMetaData.newBuilder() to construct.
    private MediaMetaData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MediaMetaData() {
      song_ = "";
      artist_ = "";
      album_ = "";
      albumart_ = com.google.protobuf.ByteString.EMPTY;
      playlist_ = "";
      duration_ = 0;
      rating_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MediaMetaData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              song_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              artist_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              album_ = bs;
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              albumart_ = input.readBytes();
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000010;
              playlist_ = bs;
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              duration_ = input.readUInt32();
              break;
            }
            case 56: {
              bitField0_ |= 0x00000040;
              rating_ = input.readUInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return gb.xxy.hr.MediaServices.internal_static_HU_MediaMetaData_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return gb.xxy.hr.MediaServices.internal_static_HU_MediaMetaData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              gb.xxy.hr.MediaServices.MediaMetaData.class, gb.xxy.hr.MediaServices.MediaMetaData.Builder.class);
    }

    private int bitField0_;
    public static final int SONG_FIELD_NUMBER = 1;
    private volatile java.lang.Object song_;
    /**
     * <code>optional string song = 1;</code>
     */
    public boolean hasSong() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string song = 1;</code>
     */
    public java.lang.String getSong() {
      java.lang.Object ref = song_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          song_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string song = 1;</code>
     */
    public com.google.protobuf.ByteString
        getSongBytes() {
      java.lang.Object ref = song_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        song_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ARTIST_FIELD_NUMBER = 2;
    private volatile java.lang.Object artist_;
    /**
     * <code>optional string artist = 2;</code>
     */
    public boolean hasArtist() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string artist = 2;</code>
     */
    public java.lang.String getArtist() {
      java.lang.Object ref = artist_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          artist_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string artist = 2;</code>
     */
    public com.google.protobuf.ByteString
        getArtistBytes() {
      java.lang.Object ref = artist_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        artist_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ALBUM_FIELD_NUMBER = 3;
    private volatile java.lang.Object album_;
    /**
     * <code>optional string album = 3;</code>
     */
    public boolean hasAlbum() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string album = 3;</code>
     */
    public java.lang.String getAlbum() {
      java.lang.Object ref = album_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          album_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string album = 3;</code>
     */
    public com.google.protobuf.ByteString
        getAlbumBytes() {
      java.lang.Object ref = album_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        album_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ALBUMART_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString albumart_;
    /**
     * <code>optional bytes albumart = 4;</code>
     */
    public boolean hasAlbumart() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional bytes albumart = 4;</code>
     */
    public com.google.protobuf.ByteString getAlbumart() {
      return albumart_;
    }

    public static final int PLAYLIST_FIELD_NUMBER = 5;
    private volatile java.lang.Object playlist_;
    /**
     * <code>optional string playlist = 5;</code>
     */
    public boolean hasPlaylist() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional string playlist = 5;</code>
     */
    public java.lang.String getPlaylist() {
      java.lang.Object ref = playlist_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          playlist_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string playlist = 5;</code>
     */
    public com.google.protobuf.ByteString
        getPlaylistBytes() {
      java.lang.Object ref = playlist_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        playlist_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DURATION_FIELD_NUMBER = 6;
    private int duration_;
    /**
     * <code>optional uint32 duration = 6;</code>
     */
    public boolean hasDuration() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional uint32 duration = 6;</code>
     */
    public int getDuration() {
      return duration_;
    }

    public static final int RATING_FIELD_NUMBER = 7;
    private int rating_;
    /**
     * <code>optional uint32 rating = 7;</code>
     */
    public boolean hasRating() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional uint32 rating = 7;</code>
     */
    public int getRating() {
      return rating_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, song_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, artist_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, album_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, albumart_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, playlist_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeUInt32(6, duration_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeUInt32(7, rating_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, song_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, artist_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, album_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, albumart_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, playlist_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(6, duration_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(7, rating_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof gb.xxy.hr.MediaServices.MediaMetaData)) {
        return super.equals(obj);
      }
      gb.xxy.hr.MediaServices.MediaMetaData other = (gb.xxy.hr.MediaServices.MediaMetaData) obj;

      boolean result = true;
      result = result && (hasSong() == other.hasSong());
      if (hasSong()) {
        result = result && getSong()
            .equals(other.getSong());
      }
      result = result && (hasArtist() == other.hasArtist());
      if (hasArtist()) {
        result = result && getArtist()
            .equals(other.getArtist());
      }
      result = result && (hasAlbum() == other.hasAlbum());
      if (hasAlbum()) {
        result = result && getAlbum()
            .equals(other.getAlbum());
      }
      result = result && (hasAlbumart() == other.hasAlbumart());
      if (hasAlbumart()) {
        result = result && getAlbumart()
            .equals(other.getAlbumart());
      }
      result = result && (hasPlaylist() == other.hasPlaylist());
      if (hasPlaylist()) {
        result = result && getPlaylist()
            .equals(other.getPlaylist());
      }
      result = result && (hasDuration() == other.hasDuration());
      if (hasDuration()) {
        result = result && (getDuration()
            == other.getDuration());
      }
      result = result && (hasRating() == other.hasRating());
      if (hasRating()) {
        result = result && (getRating()
            == other.getRating());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasSong()) {
        hash = (37 * hash) + SONG_FIELD_NUMBER;
        hash = (53 * hash) + getSong().hashCode();
      }
      if (hasArtist()) {
        hash = (37 * hash) + ARTIST_FIELD_NUMBER;
        hash = (53 * hash) + getArtist().hashCode();
      }
      if (hasAlbum()) {
        hash = (37 * hash) + ALBUM_FIELD_NUMBER;
        hash = (53 * hash) + getAlbum().hashCode();
      }
      if (hasAlbumart()) {
        hash = (37 * hash) + ALBUMART_FIELD_NUMBER;
        hash = (53 * hash) + getAlbumart().hashCode();
      }
      if (hasPlaylist()) {
        hash = (37 * hash) + PLAYLIST_FIELD_NUMBER;
        hash = (53 * hash) + getPlaylist().hashCode();
      }
      if (hasDuration()) {
        hash = (37 * hash) + DURATION_FIELD_NUMBER;
        hash = (53 * hash) + getDuration();
      }
      if (hasRating()) {
        hash = (37 * hash) + RATING_FIELD_NUMBER;
        hash = (53 * hash) + getRating();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static gb.xxy.hr.MediaServices.MediaMetaData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static gb.xxy.hr.MediaServices.MediaMetaData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static gb.xxy.hr.MediaServices.MediaMetaData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static gb.xxy.hr.MediaServices.MediaMetaData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static gb.xxy.hr.MediaServices.MediaMetaData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static gb.xxy.hr.MediaServices.MediaMetaData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static gb.xxy.hr.MediaServices.MediaMetaData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static gb.xxy.hr.MediaServices.MediaMetaData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static gb.xxy.hr.MediaServices.MediaMetaData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static gb.xxy.hr.MediaServices.MediaMetaData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(gb.xxy.hr.MediaServices.MediaMetaData prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code HU.MediaMetaData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:HU.MediaMetaData)
        gb.xxy.hr.MediaServices.MediaMetaDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return gb.xxy.hr.MediaServices.internal_static_HU_MediaMetaData_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return gb.xxy.hr.MediaServices.internal_static_HU_MediaMetaData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                gb.xxy.hr.MediaServices.MediaMetaData.class, gb.xxy.hr.MediaServices.MediaMetaData.Builder.class);
      }

      // Construct using gb.xxy.hr.MediaServices.MediaMetaData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        song_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        artist_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        album_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        albumart_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        playlist_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        duration_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        rating_ = 0;
        bitField0_ = (bitField0_ & ~0x00000040);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return gb.xxy.hr.MediaServices.internal_static_HU_MediaMetaData_descriptor;
      }

      public gb.xxy.hr.MediaServices.MediaMetaData getDefaultInstanceForType() {
        return gb.xxy.hr.MediaServices.MediaMetaData.getDefaultInstance();
      }

      public gb.xxy.hr.MediaServices.MediaMetaData build() {
        gb.xxy.hr.MediaServices.MediaMetaData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public gb.xxy.hr.MediaServices.MediaMetaData buildPartial() {
        gb.xxy.hr.MediaServices.MediaMetaData result = new gb.xxy.hr.MediaServices.MediaMetaData(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.song_ = song_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.artist_ = artist_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.album_ = album_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.albumart_ = albumart_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.playlist_ = playlist_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.duration_ = duration_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.rating_ = rating_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof gb.xxy.hr.MediaServices.MediaMetaData) {
          return mergeFrom((gb.xxy.hr.MediaServices.MediaMetaData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(gb.xxy.hr.MediaServices.MediaMetaData other) {
        if (other == gb.xxy.hr.MediaServices.MediaMetaData.getDefaultInstance()) return this;
        if (other.hasSong()) {
          bitField0_ |= 0x00000001;
          song_ = other.song_;
          onChanged();
        }
        if (other.hasArtist()) {
          bitField0_ |= 0x00000002;
          artist_ = other.artist_;
          onChanged();
        }
        if (other.hasAlbum()) {
          bitField0_ |= 0x00000004;
          album_ = other.album_;
          onChanged();
        }
        if (other.hasAlbumart()) {
          setAlbumart(other.getAlbumart());
        }
        if (other.hasPlaylist()) {
          bitField0_ |= 0x00000010;
          playlist_ = other.playlist_;
          onChanged();
        }
        if (other.hasDuration()) {
          setDuration(other.getDuration());
        }
        if (other.hasRating()) {
          setRating(other.getRating());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        gb.xxy.hr.MediaServices.MediaMetaData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (gb.xxy.hr.MediaServices.MediaMetaData) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object song_ = "";
      /**
       * <code>optional string song = 1;</code>
       */
      public boolean hasSong() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string song = 1;</code>
       */
      public java.lang.String getSong() {
        java.lang.Object ref = song_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            song_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string song = 1;</code>
       */
      public com.google.protobuf.ByteString
          getSongBytes() {
        java.lang.Object ref = song_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          song_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string song = 1;</code>
       */
      public Builder setSong(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        song_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string song = 1;</code>
       */
      public Builder clearSong() {
        bitField0_ = (bitField0_ & ~0x00000001);
        song_ = getDefaultInstance().getSong();
        onChanged();
        return this;
      }
      /**
       * <code>optional string song = 1;</code>
       */
      public Builder setSongBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        song_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object artist_ = "";
      /**
       * <code>optional string artist = 2;</code>
       */
      public boolean hasArtist() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string artist = 2;</code>
       */
      public java.lang.String getArtist() {
        java.lang.Object ref = artist_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            artist_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string artist = 2;</code>
       */
      public com.google.protobuf.ByteString
          getArtistBytes() {
        java.lang.Object ref = artist_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          artist_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string artist = 2;</code>
       */
      public Builder setArtist(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        artist_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string artist = 2;</code>
       */
      public Builder clearArtist() {
        bitField0_ = (bitField0_ & ~0x00000002);
        artist_ = getDefaultInstance().getArtist();
        onChanged();
        return this;
      }
      /**
       * <code>optional string artist = 2;</code>
       */
      public Builder setArtistBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        artist_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object album_ = "";
      /**
       * <code>optional string album = 3;</code>
       */
      public boolean hasAlbum() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string album = 3;</code>
       */
      public java.lang.String getAlbum() {
        java.lang.Object ref = album_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            album_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string album = 3;</code>
       */
      public com.google.protobuf.ByteString
          getAlbumBytes() {
        java.lang.Object ref = album_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          album_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string album = 3;</code>
       */
      public Builder setAlbum(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        album_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string album = 3;</code>
       */
      public Builder clearAlbum() {
        bitField0_ = (bitField0_ & ~0x00000004);
        album_ = getDefaultInstance().getAlbum();
        onChanged();
        return this;
      }
      /**
       * <code>optional string album = 3;</code>
       */
      public Builder setAlbumBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        album_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString albumart_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes albumart = 4;</code>
       */
      public boolean hasAlbumart() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional bytes albumart = 4;</code>
       */
      public com.google.protobuf.ByteString getAlbumart() {
        return albumart_;
      }
      /**
       * <code>optional bytes albumart = 4;</code>
       */
      public Builder setAlbumart(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        albumart_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes albumart = 4;</code>
       */
      public Builder clearAlbumart() {
        bitField0_ = (bitField0_ & ~0x00000008);
        albumart_ = getDefaultInstance().getAlbumart();
        onChanged();
        return this;
      }

      private java.lang.Object playlist_ = "";
      /**
       * <code>optional string playlist = 5;</code>
       */
      public boolean hasPlaylist() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional string playlist = 5;</code>
       */
      public java.lang.String getPlaylist() {
        java.lang.Object ref = playlist_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            playlist_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string playlist = 5;</code>
       */
      public com.google.protobuf.ByteString
          getPlaylistBytes() {
        java.lang.Object ref = playlist_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          playlist_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string playlist = 5;</code>
       */
      public Builder setPlaylist(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        playlist_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string playlist = 5;</code>
       */
      public Builder clearPlaylist() {
        bitField0_ = (bitField0_ & ~0x00000010);
        playlist_ = getDefaultInstance().getPlaylist();
        onChanged();
        return this;
      }
      /**
       * <code>optional string playlist = 5;</code>
       */
      public Builder setPlaylistBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        playlist_ = value;
        onChanged();
        return this;
      }

      private int duration_ ;
      /**
       * <code>optional uint32 duration = 6;</code>
       */
      public boolean hasDuration() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional uint32 duration = 6;</code>
       */
      public int getDuration() {
        return duration_;
      }
      /**
       * <code>optional uint32 duration = 6;</code>
       */
      public Builder setDuration(int value) {
        bitField0_ |= 0x00000020;
        duration_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 duration = 6;</code>
       */
      public Builder clearDuration() {
        bitField0_ = (bitField0_ & ~0x00000020);
        duration_ = 0;
        onChanged();
        return this;
      }

      private int rating_ ;
      /**
       * <code>optional uint32 rating = 7;</code>
       */
      public boolean hasRating() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional uint32 rating = 7;</code>
       */
      public int getRating() {
        return rating_;
      }
      /**
       * <code>optional uint32 rating = 7;</code>
       */
      public Builder setRating(int value) {
        bitField0_ |= 0x00000040;
        rating_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 rating = 7;</code>
       */
      public Builder clearRating() {
        bitField0_ = (bitField0_ & ~0x00000040);
        rating_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:HU.MediaMetaData)
    }

    // @@protoc_insertion_point(class_scope:HU.MediaMetaData)
    private static final gb.xxy.hr.MediaServices.MediaMetaData DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new gb.xxy.hr.MediaServices.MediaMetaData();
    }

    public static gb.xxy.hr.MediaServices.MediaMetaData getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<MediaMetaData>
        PARSER = new com.google.protobuf.AbstractParser<MediaMetaData>() {
      public MediaMetaData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new MediaMetaData(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MediaMetaData> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MediaMetaData> getParserForType() {
      return PARSER;
    }

    public gb.xxy.hr.MediaServices.MediaMetaData getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_HU_MediaService_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_HU_MediaService_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_HU_MediaMetaData_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_HU_MediaMetaData_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013media.proto\022\002HU\"\275\001\n\014MediaService\022\'\n\005st" +
      "ate\030\001 \001(\0162\030.HU.MediaService.MedStat\022\016\n\006s" +
      "ource\030\002 \001(\t\022\017\n\007seconds\030\003 \001(\r\022\017\n\007shuffle\030" +
      "\004 \001(\010\022\016\n\006repeat\030\005 \001(\010\022\022\n\nrepeat_one\030\006 \001(" +
      "\010\".\n\007MedStat\022\t\n\005PAUSE\020\000\022\013\n\007STOPPED\020\001\022\013\n\007" +
      "PLAYING\020\003\"\202\001\n\rMediaMetaData\022\014\n\004song\030\001 \001(" +
      "\t\022\016\n\006artist\030\002 \001(\t\022\r\n\005album\030\003 \001(\t\022\020\n\010albu" +
      "mart\030\004 \001(\014\022\020\n\010playlist\030\005 \001(\t\022\020\n\010duration" +
      "\030\006 \001(\r\022\016\n\006rating\030\007 \001(\r*p\n\013MediaStatus\022!\n" +
      "\033MSG_TYPE_SENSORSTARTREQUEST\020\201\200\002\022\"\n\034MSG_",
      "TYPE_SENSORSTARTRESPONSE\020\202\200\002\022\032\n\024MSG_TYPE" +
      "_SENSOREVENT\020\203\200\002B\032\n\tgb.xxy.hrB\rMediaServ" +
      "ices"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_HU_MediaService_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_HU_MediaService_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_HU_MediaService_descriptor,
        new java.lang.String[] { "State", "Source", "Seconds", "Shuffle", "Repeat", "RepeatOne", });
    internal_static_HU_MediaMetaData_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_HU_MediaMetaData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_HU_MediaMetaData_descriptor,
        new java.lang.String[] { "Song", "Artist", "Album", "Albumart", "Playlist", "Duration", "Rating", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
