// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: navigation.proto

package gb.xxy.hr;

public final class NavStatServices {
  private NavStatServices() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code HU.NavMes}
   */
  public enum NavMes
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>MSG_TYPE_SENSORSTARTREQUEST = 32772;</code>
     */
    MSG_TYPE_SENSORSTARTREQUEST(32772),
    /**
     * <code>MSG_TYPE_SENSORSTARTRESPONSE = 32773;</code>
     */
    MSG_TYPE_SENSORSTARTRESPONSE(32773),
    ;

    /**
     * <code>MSG_TYPE_SENSORSTARTREQUEST = 32772;</code>
     */
    public static final int MSG_TYPE_SENSORSTARTREQUEST_VALUE = 32772;
    /**
     * <code>MSG_TYPE_SENSORSTARTRESPONSE = 32773;</code>
     */
    public static final int MSG_TYPE_SENSORSTARTRESPONSE_VALUE = 32773;


    public final int getNumber() {
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static NavMes valueOf(int value) {
      return forNumber(value);
    }

    public static NavMes forNumber(int value) {
      switch (value) {
        case 32772: return MSG_TYPE_SENSORSTARTREQUEST;
        case 32773: return MSG_TYPE_SENSORSTARTRESPONSE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<NavMes>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        NavMes> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<NavMes>() {
            public NavMes findValueByNumber(int number) {
              return NavMes.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return gb.xxy.hr.NavStatServices.getDescriptor().getEnumTypes().get(0);
    }

    private static final NavMes[] VALUES = values();

    public static NavMes valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private NavMes(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:HU.NavMes)
  }

  public interface NextTurnDetailOrBuilder extends
      // @@protoc_insertion_point(interface_extends:HU.NextTurnDetail)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string road = 1;</code>
     */
    boolean hasRoad();
    /**
     * <code>optional string road = 1;</code>
     */
    java.lang.String getRoad();
    /**
     * <code>optional string road = 1;</code>
     */
    com.google.protobuf.ByteString
        getRoadBytes();

    /**
     * <code>optional .HU.NextTurnDetail.Side side = 2;</code>
     */
    boolean hasSide();
    /**
     * <code>optional .HU.NextTurnDetail.Side side = 2;</code>
     */
    gb.xxy.hr.NavStatServices.NextTurnDetail.Side getSide();

    /**
     * <code>optional .HU.NextTurnDetail.NextEvent nextturn = 3;</code>
     */
    boolean hasNextturn();
    /**
     * <code>optional .HU.NextTurnDetail.NextEvent nextturn = 3;</code>
     */
    gb.xxy.hr.NavStatServices.NextTurnDetail.NextEvent getNextturn();

    /**
     * <code>optional bytes turngraph = 4;</code>
     */
    boolean hasTurngraph();
    /**
     * <code>optional bytes turngraph = 4;</code>
     */
    com.google.protobuf.ByteString getTurngraph();

    /**
     * <code>optional uint32 trunnumer = 5;</code>
     */
    boolean hasTrunnumer();
    /**
     * <code>optional uint32 trunnumer = 5;</code>
     */
    int getTrunnumer();

    /**
     * <code>optional uint32 turnangel = 6;</code>
     */
    boolean hasTurnangel();
    /**
     * <code>optional uint32 turnangel = 6;</code>
     */
    int getTurnangel();
  }
  /**
   * Protobuf type {@code HU.NextTurnDetail}
   */
  public  static final class NextTurnDetail extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:HU.NextTurnDetail)
      NextTurnDetailOrBuilder {
    // Use NextTurnDetail.newBuilder() to construct.
    private NextTurnDetail(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private NextTurnDetail() {
      road_ = "";
      side_ = 1;
      nextturn_ = 0;
      turngraph_ = com.google.protobuf.ByteString.EMPTY;
      trunnumer_ = 0;
      turnangel_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private NextTurnDetail(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              road_ = bs;
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
              gb.xxy.hr.NavStatServices.NextTurnDetail.Side value = gb.xxy.hr.NavStatServices.NextTurnDetail.Side.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                bitField0_ |= 0x00000002;
                side_ = rawValue;
              }
              break;
            }
            case 24: {
              int rawValue = input.readEnum();
              gb.xxy.hr.NavStatServices.NextTurnDetail.NextEvent value = gb.xxy.hr.NavStatServices.NextTurnDetail.NextEvent.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(3, rawValue);
              } else {
                bitField0_ |= 0x00000004;
                nextturn_ = rawValue;
              }
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              turngraph_ = input.readBytes();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              trunnumer_ = input.readUInt32();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              turnangel_ = input.readUInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return gb.xxy.hr.NavStatServices.internal_static_HU_NextTurnDetail_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return gb.xxy.hr.NavStatServices.internal_static_HU_NextTurnDetail_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              gb.xxy.hr.NavStatServices.NextTurnDetail.class, gb.xxy.hr.NavStatServices.NextTurnDetail.Builder.class);
    }

    /**
     * Protobuf enum {@code HU.NextTurnDetail.Side}
     */
    public enum Side
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>LEFT = 1;</code>
       */
      LEFT(1),
      /**
       * <code>RIGHT = 2;</code>
       */
      RIGHT(2),
      /**
       * <code>UNSPECIFIED = 3;</code>
       */
      UNSPECIFIED(3),
      ;

      /**
       * <code>LEFT = 1;</code>
       */
      public static final int LEFT_VALUE = 1;
      /**
       * <code>RIGHT = 2;</code>
       */
      public static final int RIGHT_VALUE = 2;
      /**
       * <code>UNSPECIFIED = 3;</code>
       */
      public static final int UNSPECIFIED_VALUE = 3;


      public final int getNumber() {
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static Side valueOf(int value) {
        return forNumber(value);
      }

      public static Side forNumber(int value) {
        switch (value) {
          case 1: return LEFT;
          case 2: return RIGHT;
          case 3: return UNSPECIFIED;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Side>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Side> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Side>() {
              public Side findValueByNumber(int number) {
                return Side.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return gb.xxy.hr.NavStatServices.NextTurnDetail.getDescriptor().getEnumTypes().get(0);
      }

      private static final Side[] VALUES = values();

      public static Side valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private Side(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:HU.NextTurnDetail.Side)
    }

    /**
     * Protobuf enum {@code HU.NextTurnDetail.NextEvent}
     */
    public enum NextEvent
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>UNKNOWN = 0;</code>
       */
      UNKNOWN(0),
      /**
       * <code>DEPARTE = 1;</code>
       */
      DEPARTE(1),
      /**
       * <code>NAME_CHANGE = 2;</code>
       */
      NAME_CHANGE(2),
      /**
       * <code>SLIGHT_TURN = 3;</code>
       */
      SLIGHT_TURN(3),
      /**
       * <code>TURN = 4;</code>
       */
      TURN(4),
      /**
       * <code>SHARP_TURN = 5;</code>
       */
      SHARP_TURN(5),
      /**
       * <code>UTURN = 6;</code>
       */
      UTURN(6),
      /**
       * <code>ONRAMPE = 7;</code>
       */
      ONRAMPE(7),
      /**
       * <code>OFFRAMP = 8;</code>
       */
      OFFRAMP(8),
      /**
       * <code>FORME = 9;</code>
       */
      FORME(9),
      /**
       * <code>MERGE = 10;</code>
       */
      MERGE(10),
      /**
       * <code>ROUNDABOUT_ENTER = 11;</code>
       */
      ROUNDABOUT_ENTER(11),
      /**
       * <code>ROUNDABOUT_EXIT = 12;</code>
       */
      ROUNDABOUT_EXIT(12),
      /**
       * <code>ROUNDABOUT_ENTER_AND_EXIT = 13;</code>
       */
      ROUNDABOUT_ENTER_AND_EXIT(13),
      /**
       * <code>STRAIGHTE = 14;</code>
       */
      STRAIGHTE(14),
      /**
       * <code>FERRY_BOAT = 16;</code>
       */
      FERRY_BOAT(16),
      /**
       * <code>FERRY_TRAINE = 17;</code>
       */
      FERRY_TRAINE(17),
      /**
       * <code>DESTINATION = 18;</code>
       */
      DESTINATION(18),
      ;

      /**
       * <code>UNKNOWN = 0;</code>
       */
      public static final int UNKNOWN_VALUE = 0;
      /**
       * <code>DEPARTE = 1;</code>
       */
      public static final int DEPARTE_VALUE = 1;
      /**
       * <code>NAME_CHANGE = 2;</code>
       */
      public static final int NAME_CHANGE_VALUE = 2;
      /**
       * <code>SLIGHT_TURN = 3;</code>
       */
      public static final int SLIGHT_TURN_VALUE = 3;
      /**
       * <code>TURN = 4;</code>
       */
      public static final int TURN_VALUE = 4;
      /**
       * <code>SHARP_TURN = 5;</code>
       */
      public static final int SHARP_TURN_VALUE = 5;
      /**
       * <code>UTURN = 6;</code>
       */
      public static final int UTURN_VALUE = 6;
      /**
       * <code>ONRAMPE = 7;</code>
       */
      public static final int ONRAMPE_VALUE = 7;
      /**
       * <code>OFFRAMP = 8;</code>
       */
      public static final int OFFRAMP_VALUE = 8;
      /**
       * <code>FORME = 9;</code>
       */
      public static final int FORME_VALUE = 9;
      /**
       * <code>MERGE = 10;</code>
       */
      public static final int MERGE_VALUE = 10;
      /**
       * <code>ROUNDABOUT_ENTER = 11;</code>
       */
      public static final int ROUNDABOUT_ENTER_VALUE = 11;
      /**
       * <code>ROUNDABOUT_EXIT = 12;</code>
       */
      public static final int ROUNDABOUT_EXIT_VALUE = 12;
      /**
       * <code>ROUNDABOUT_ENTER_AND_EXIT = 13;</code>
       */
      public static final int ROUNDABOUT_ENTER_AND_EXIT_VALUE = 13;
      /**
       * <code>STRAIGHTE = 14;</code>
       */
      public static final int STRAIGHTE_VALUE = 14;
      /**
       * <code>FERRY_BOAT = 16;</code>
       */
      public static final int FERRY_BOAT_VALUE = 16;
      /**
       * <code>FERRY_TRAINE = 17;</code>
       */
      public static final int FERRY_TRAINE_VALUE = 17;
      /**
       * <code>DESTINATION = 18;</code>
       */
      public static final int DESTINATION_VALUE = 18;


      public final int getNumber() {
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static NextEvent valueOf(int value) {
        return forNumber(value);
      }

      public static NextEvent forNumber(int value) {
        switch (value) {
          case 0: return UNKNOWN;
          case 1: return DEPARTE;
          case 2: return NAME_CHANGE;
          case 3: return SLIGHT_TURN;
          case 4: return TURN;
          case 5: return SHARP_TURN;
          case 6: return UTURN;
          case 7: return ONRAMPE;
          case 8: return OFFRAMP;
          case 9: return FORME;
          case 10: return MERGE;
          case 11: return ROUNDABOUT_ENTER;
          case 12: return ROUNDABOUT_EXIT;
          case 13: return ROUNDABOUT_ENTER_AND_EXIT;
          case 14: return STRAIGHTE;
          case 16: return FERRY_BOAT;
          case 17: return FERRY_TRAINE;
          case 18: return DESTINATION;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<NextEvent>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          NextEvent> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<NextEvent>() {
              public NextEvent findValueByNumber(int number) {
                return NextEvent.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return gb.xxy.hr.NavStatServices.NextTurnDetail.getDescriptor().getEnumTypes().get(1);
      }

      private static final NextEvent[] VALUES = values();

      public static NextEvent valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private NextEvent(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:HU.NextTurnDetail.NextEvent)
    }

    private int bitField0_;
    public static final int ROAD_FIELD_NUMBER = 1;
    private volatile java.lang.Object road_;
    /**
     * <code>optional string road = 1;</code>
     */
    public boolean hasRoad() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string road = 1;</code>
     */
    public java.lang.String getRoad() {
      java.lang.Object ref = road_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          road_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string road = 1;</code>
     */
    public com.google.protobuf.ByteString
        getRoadBytes() {
      java.lang.Object ref = road_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        road_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SIDE_FIELD_NUMBER = 2;
    private int side_;
    /**
     * <code>optional .HU.NextTurnDetail.Side side = 2;</code>
     */
    public boolean hasSide() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional .HU.NextTurnDetail.Side side = 2;</code>
     */
    public gb.xxy.hr.NavStatServices.NextTurnDetail.Side getSide() {
      gb.xxy.hr.NavStatServices.NextTurnDetail.Side result = gb.xxy.hr.NavStatServices.NextTurnDetail.Side.valueOf(side_);
      return result == null ? gb.xxy.hr.NavStatServices.NextTurnDetail.Side.LEFT : result;
    }

    public static final int NEXTTURN_FIELD_NUMBER = 3;
    private int nextturn_;
    /**
     * <code>optional .HU.NextTurnDetail.NextEvent nextturn = 3;</code>
     */
    public boolean hasNextturn() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional .HU.NextTurnDetail.NextEvent nextturn = 3;</code>
     */
    public gb.xxy.hr.NavStatServices.NextTurnDetail.NextEvent getNextturn() {
      gb.xxy.hr.NavStatServices.NextTurnDetail.NextEvent result = gb.xxy.hr.NavStatServices.NextTurnDetail.NextEvent.valueOf(nextturn_);
      return result == null ? gb.xxy.hr.NavStatServices.NextTurnDetail.NextEvent.UNKNOWN : result;
    }

    public static final int TURNGRAPH_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString turngraph_;
    /**
     * <code>optional bytes turngraph = 4;</code>
     */
    public boolean hasTurngraph() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional bytes turngraph = 4;</code>
     */
    public com.google.protobuf.ByteString getTurngraph() {
      return turngraph_;
    }

    public static final int TRUNNUMER_FIELD_NUMBER = 5;
    private int trunnumer_;
    /**
     * <code>optional uint32 trunnumer = 5;</code>
     */
    public boolean hasTrunnumer() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional uint32 trunnumer = 5;</code>
     */
    public int getTrunnumer() {
      return trunnumer_;
    }

    public static final int TURNANGEL_FIELD_NUMBER = 6;
    private int turnangel_;
    /**
     * <code>optional uint32 turnangel = 6;</code>
     */
    public boolean hasTurnangel() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional uint32 turnangel = 6;</code>
     */
    public int getTurnangel() {
      return turnangel_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, road_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeEnum(2, side_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeEnum(3, nextturn_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, turngraph_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeUInt32(5, trunnumer_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeUInt32(6, turnangel_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, road_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, side_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, nextturn_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, turngraph_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(5, trunnumer_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(6, turnangel_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof gb.xxy.hr.NavStatServices.NextTurnDetail)) {
        return super.equals(obj);
      }
      gb.xxy.hr.NavStatServices.NextTurnDetail other = (gb.xxy.hr.NavStatServices.NextTurnDetail) obj;

      boolean result = true;
      result = result && (hasRoad() == other.hasRoad());
      if (hasRoad()) {
        result = result && getRoad()
            .equals(other.getRoad());
      }
      result = result && (hasSide() == other.hasSide());
      if (hasSide()) {
        result = result && side_ == other.side_;
      }
      result = result && (hasNextturn() == other.hasNextturn());
      if (hasNextturn()) {
        result = result && nextturn_ == other.nextturn_;
      }
      result = result && (hasTurngraph() == other.hasTurngraph());
      if (hasTurngraph()) {
        result = result && getTurngraph()
            .equals(other.getTurngraph());
      }
      result = result && (hasTrunnumer() == other.hasTrunnumer());
      if (hasTrunnumer()) {
        result = result && (getTrunnumer()
            == other.getTrunnumer());
      }
      result = result && (hasTurnangel() == other.hasTurnangel());
      if (hasTurnangel()) {
        result = result && (getTurnangel()
            == other.getTurnangel());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasRoad()) {
        hash = (37 * hash) + ROAD_FIELD_NUMBER;
        hash = (53 * hash) + getRoad().hashCode();
      }
      if (hasSide()) {
        hash = (37 * hash) + SIDE_FIELD_NUMBER;
        hash = (53 * hash) + side_;
      }
      if (hasNextturn()) {
        hash = (37 * hash) + NEXTTURN_FIELD_NUMBER;
        hash = (53 * hash) + nextturn_;
      }
      if (hasTurngraph()) {
        hash = (37 * hash) + TURNGRAPH_FIELD_NUMBER;
        hash = (53 * hash) + getTurngraph().hashCode();
      }
      if (hasTrunnumer()) {
        hash = (37 * hash) + TRUNNUMER_FIELD_NUMBER;
        hash = (53 * hash) + getTrunnumer();
      }
      if (hasTurnangel()) {
        hash = (37 * hash) + TURNANGEL_FIELD_NUMBER;
        hash = (53 * hash) + getTurnangel();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static gb.xxy.hr.NavStatServices.NextTurnDetail parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static gb.xxy.hr.NavStatServices.NextTurnDetail parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static gb.xxy.hr.NavStatServices.NextTurnDetail parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static gb.xxy.hr.NavStatServices.NextTurnDetail parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static gb.xxy.hr.NavStatServices.NextTurnDetail parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static gb.xxy.hr.NavStatServices.NextTurnDetail parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static gb.xxy.hr.NavStatServices.NextTurnDetail parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static gb.xxy.hr.NavStatServices.NextTurnDetail parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static gb.xxy.hr.NavStatServices.NextTurnDetail parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static gb.xxy.hr.NavStatServices.NextTurnDetail parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(gb.xxy.hr.NavStatServices.NextTurnDetail prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code HU.NextTurnDetail}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:HU.NextTurnDetail)
        gb.xxy.hr.NavStatServices.NextTurnDetailOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return gb.xxy.hr.NavStatServices.internal_static_HU_NextTurnDetail_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return gb.xxy.hr.NavStatServices.internal_static_HU_NextTurnDetail_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                gb.xxy.hr.NavStatServices.NextTurnDetail.class, gb.xxy.hr.NavStatServices.NextTurnDetail.Builder.class);
      }

      // Construct using gb.xxy.hr.NavStatServices.NextTurnDetail.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        road_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        side_ = 1;
        bitField0_ = (bitField0_ & ~0x00000002);
        nextturn_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        turngraph_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        trunnumer_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        turnangel_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return gb.xxy.hr.NavStatServices.internal_static_HU_NextTurnDetail_descriptor;
      }

      public gb.xxy.hr.NavStatServices.NextTurnDetail getDefaultInstanceForType() {
        return gb.xxy.hr.NavStatServices.NextTurnDetail.getDefaultInstance();
      }

      public gb.xxy.hr.NavStatServices.NextTurnDetail build() {
        gb.xxy.hr.NavStatServices.NextTurnDetail result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public gb.xxy.hr.NavStatServices.NextTurnDetail buildPartial() {
        gb.xxy.hr.NavStatServices.NextTurnDetail result = new gb.xxy.hr.NavStatServices.NextTurnDetail(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.road_ = road_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.side_ = side_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.nextturn_ = nextturn_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.turngraph_ = turngraph_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.trunnumer_ = trunnumer_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.turnangel_ = turnangel_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof gb.xxy.hr.NavStatServices.NextTurnDetail) {
          return mergeFrom((gb.xxy.hr.NavStatServices.NextTurnDetail)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(gb.xxy.hr.NavStatServices.NextTurnDetail other) {
        if (other == gb.xxy.hr.NavStatServices.NextTurnDetail.getDefaultInstance()) return this;
        if (other.hasRoad()) {
          bitField0_ |= 0x00000001;
          road_ = other.road_;
          onChanged();
        }
        if (other.hasSide()) {
          setSide(other.getSide());
        }
        if (other.hasNextturn()) {
          setNextturn(other.getNextturn());
        }
        if (other.hasTurngraph()) {
          setTurngraph(other.getTurngraph());
        }
        if (other.hasTrunnumer()) {
          setTrunnumer(other.getTrunnumer());
        }
        if (other.hasTurnangel()) {
          setTurnangel(other.getTurnangel());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        gb.xxy.hr.NavStatServices.NextTurnDetail parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (gb.xxy.hr.NavStatServices.NextTurnDetail) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object road_ = "";
      /**
       * <code>optional string road = 1;</code>
       */
      public boolean hasRoad() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string road = 1;</code>
       */
      public java.lang.String getRoad() {
        java.lang.Object ref = road_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            road_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string road = 1;</code>
       */
      public com.google.protobuf.ByteString
          getRoadBytes() {
        java.lang.Object ref = road_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          road_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string road = 1;</code>
       */
      public Builder setRoad(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        road_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string road = 1;</code>
       */
      public Builder clearRoad() {
        bitField0_ = (bitField0_ & ~0x00000001);
        road_ = getDefaultInstance().getRoad();
        onChanged();
        return this;
      }
      /**
       * <code>optional string road = 1;</code>
       */
      public Builder setRoadBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        road_ = value;
        onChanged();
        return this;
      }

      private int side_ = 1;
      /**
       * <code>optional .HU.NextTurnDetail.Side side = 2;</code>
       */
      public boolean hasSide() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional .HU.NextTurnDetail.Side side = 2;</code>
       */
      public gb.xxy.hr.NavStatServices.NextTurnDetail.Side getSide() {
        gb.xxy.hr.NavStatServices.NextTurnDetail.Side result = gb.xxy.hr.NavStatServices.NextTurnDetail.Side.valueOf(side_);
        return result == null ? gb.xxy.hr.NavStatServices.NextTurnDetail.Side.LEFT : result;
      }
      /**
       * <code>optional .HU.NextTurnDetail.Side side = 2;</code>
       */
      public Builder setSide(gb.xxy.hr.NavStatServices.NextTurnDetail.Side value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        side_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional .HU.NextTurnDetail.Side side = 2;</code>
       */
      public Builder clearSide() {
        bitField0_ = (bitField0_ & ~0x00000002);
        side_ = 1;
        onChanged();
        return this;
      }

      private int nextturn_ = 0;
      /**
       * <code>optional .HU.NextTurnDetail.NextEvent nextturn = 3;</code>
       */
      public boolean hasNextturn() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional .HU.NextTurnDetail.NextEvent nextturn = 3;</code>
       */
      public gb.xxy.hr.NavStatServices.NextTurnDetail.NextEvent getNextturn() {
        gb.xxy.hr.NavStatServices.NextTurnDetail.NextEvent result = gb.xxy.hr.NavStatServices.NextTurnDetail.NextEvent.valueOf(nextturn_);
        return result == null ? gb.xxy.hr.NavStatServices.NextTurnDetail.NextEvent.UNKNOWN : result;
      }
      /**
       * <code>optional .HU.NextTurnDetail.NextEvent nextturn = 3;</code>
       */
      public Builder setNextturn(gb.xxy.hr.NavStatServices.NextTurnDetail.NextEvent value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000004;
        nextturn_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional .HU.NextTurnDetail.NextEvent nextturn = 3;</code>
       */
      public Builder clearNextturn() {
        bitField0_ = (bitField0_ & ~0x00000004);
        nextturn_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString turngraph_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes turngraph = 4;</code>
       */
      public boolean hasTurngraph() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional bytes turngraph = 4;</code>
       */
      public com.google.protobuf.ByteString getTurngraph() {
        return turngraph_;
      }
      /**
       * <code>optional bytes turngraph = 4;</code>
       */
      public Builder setTurngraph(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        turngraph_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes turngraph = 4;</code>
       */
      public Builder clearTurngraph() {
        bitField0_ = (bitField0_ & ~0x00000008);
        turngraph_ = getDefaultInstance().getTurngraph();
        onChanged();
        return this;
      }

      private int trunnumer_ ;
      /**
       * <code>optional uint32 trunnumer = 5;</code>
       */
      public boolean hasTrunnumer() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional uint32 trunnumer = 5;</code>
       */
      public int getTrunnumer() {
        return trunnumer_;
      }
      /**
       * <code>optional uint32 trunnumer = 5;</code>
       */
      public Builder setTrunnumer(int value) {
        bitField0_ |= 0x00000010;
        trunnumer_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 trunnumer = 5;</code>
       */
      public Builder clearTrunnumer() {
        bitField0_ = (bitField0_ & ~0x00000010);
        trunnumer_ = 0;
        onChanged();
        return this;
      }

      private int turnangel_ ;
      /**
       * <code>optional uint32 turnangel = 6;</code>
       */
      public boolean hasTurnangel() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional uint32 turnangel = 6;</code>
       */
      public int getTurnangel() {
        return turnangel_;
      }
      /**
       * <code>optional uint32 turnangel = 6;</code>
       */
      public Builder setTurnangel(int value) {
        bitField0_ |= 0x00000020;
        turnangel_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 turnangel = 6;</code>
       */
      public Builder clearTurnangel() {
        bitField0_ = (bitField0_ & ~0x00000020);
        turnangel_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:HU.NextTurnDetail)
    }

    // @@protoc_insertion_point(class_scope:HU.NextTurnDetail)
    private static final gb.xxy.hr.NavStatServices.NextTurnDetail DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new gb.xxy.hr.NavStatServices.NextTurnDetail();
    }

    public static gb.xxy.hr.NavStatServices.NextTurnDetail getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<NextTurnDetail>
        PARSER = new com.google.protobuf.AbstractParser<NextTurnDetail>() {
      public NextTurnDetail parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new NextTurnDetail(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<NextTurnDetail> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<NextTurnDetail> getParserForType() {
      return PARSER;
    }

    public gb.xxy.hr.NavStatServices.NextTurnDetail getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface NextturndistnaceeventOrBuilder extends
      // @@protoc_insertion_point(interface_extends:HU.Nextturndistnaceevent)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional uint32 distance = 1;</code>
     */
    boolean hasDistance();
    /**
     * <code>optional uint32 distance = 1;</code>
     */
    int getDistance();

    /**
     * <code>optional uint32 time = 2;</code>
     */
    boolean hasTime();
    /**
     * <code>optional uint32 time = 2;</code>
     */
    int getTime();
  }
  /**
   * Protobuf type {@code HU.Nextturndistnaceevent}
   */
  public  static final class Nextturndistnaceevent extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:HU.Nextturndistnaceevent)
      NextturndistnaceeventOrBuilder {
    // Use Nextturndistnaceevent.newBuilder() to construct.
    private Nextturndistnaceevent(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Nextturndistnaceevent() {
      distance_ = 0;
      time_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Nextturndistnaceevent(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              distance_ = input.readUInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              time_ = input.readUInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return gb.xxy.hr.NavStatServices.internal_static_HU_Nextturndistnaceevent_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return gb.xxy.hr.NavStatServices.internal_static_HU_Nextturndistnaceevent_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              gb.xxy.hr.NavStatServices.Nextturndistnaceevent.class, gb.xxy.hr.NavStatServices.Nextturndistnaceevent.Builder.class);
    }

    private int bitField0_;
    public static final int DISTANCE_FIELD_NUMBER = 1;
    private int distance_;
    /**
     * <code>optional uint32 distance = 1;</code>
     */
    public boolean hasDistance() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional uint32 distance = 1;</code>
     */
    public int getDistance() {
      return distance_;
    }

    public static final int TIME_FIELD_NUMBER = 2;
    private int time_;
    /**
     * <code>optional uint32 time = 2;</code>
     */
    public boolean hasTime() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional uint32 time = 2;</code>
     */
    public int getTime() {
      return time_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt32(1, distance_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt32(2, time_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, distance_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, time_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof gb.xxy.hr.NavStatServices.Nextturndistnaceevent)) {
        return super.equals(obj);
      }
      gb.xxy.hr.NavStatServices.Nextturndistnaceevent other = (gb.xxy.hr.NavStatServices.Nextturndistnaceevent) obj;

      boolean result = true;
      result = result && (hasDistance() == other.hasDistance());
      if (hasDistance()) {
        result = result && (getDistance()
            == other.getDistance());
      }
      result = result && (hasTime() == other.hasTime());
      if (hasTime()) {
        result = result && (getTime()
            == other.getTime());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasDistance()) {
        hash = (37 * hash) + DISTANCE_FIELD_NUMBER;
        hash = (53 * hash) + getDistance();
      }
      if (hasTime()) {
        hash = (37 * hash) + TIME_FIELD_NUMBER;
        hash = (53 * hash) + getTime();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static gb.xxy.hr.NavStatServices.Nextturndistnaceevent parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static gb.xxy.hr.NavStatServices.Nextturndistnaceevent parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static gb.xxy.hr.NavStatServices.Nextturndistnaceevent parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static gb.xxy.hr.NavStatServices.Nextturndistnaceevent parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static gb.xxy.hr.NavStatServices.Nextturndistnaceevent parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static gb.xxy.hr.NavStatServices.Nextturndistnaceevent parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static gb.xxy.hr.NavStatServices.Nextturndistnaceevent parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static gb.xxy.hr.NavStatServices.Nextturndistnaceevent parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static gb.xxy.hr.NavStatServices.Nextturndistnaceevent parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static gb.xxy.hr.NavStatServices.Nextturndistnaceevent parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(gb.xxy.hr.NavStatServices.Nextturndistnaceevent prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code HU.Nextturndistnaceevent}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:HU.Nextturndistnaceevent)
        gb.xxy.hr.NavStatServices.NextturndistnaceeventOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return gb.xxy.hr.NavStatServices.internal_static_HU_Nextturndistnaceevent_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return gb.xxy.hr.NavStatServices.internal_static_HU_Nextturndistnaceevent_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                gb.xxy.hr.NavStatServices.Nextturndistnaceevent.class, gb.xxy.hr.NavStatServices.Nextturndistnaceevent.Builder.class);
      }

      // Construct using gb.xxy.hr.NavStatServices.Nextturndistnaceevent.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        distance_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        time_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return gb.xxy.hr.NavStatServices.internal_static_HU_Nextturndistnaceevent_descriptor;
      }

      public gb.xxy.hr.NavStatServices.Nextturndistnaceevent getDefaultInstanceForType() {
        return gb.xxy.hr.NavStatServices.Nextturndistnaceevent.getDefaultInstance();
      }

      public gb.xxy.hr.NavStatServices.Nextturndistnaceevent build() {
        gb.xxy.hr.NavStatServices.Nextturndistnaceevent result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public gb.xxy.hr.NavStatServices.Nextturndistnaceevent buildPartial() {
        gb.xxy.hr.NavStatServices.Nextturndistnaceevent result = new gb.xxy.hr.NavStatServices.Nextturndistnaceevent(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.distance_ = distance_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.time_ = time_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof gb.xxy.hr.NavStatServices.Nextturndistnaceevent) {
          return mergeFrom((gb.xxy.hr.NavStatServices.Nextturndistnaceevent)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(gb.xxy.hr.NavStatServices.Nextturndistnaceevent other) {
        if (other == gb.xxy.hr.NavStatServices.Nextturndistnaceevent.getDefaultInstance()) return this;
        if (other.hasDistance()) {
          setDistance(other.getDistance());
        }
        if (other.hasTime()) {
          setTime(other.getTime());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        gb.xxy.hr.NavStatServices.Nextturndistnaceevent parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (gb.xxy.hr.NavStatServices.Nextturndistnaceevent) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int distance_ ;
      /**
       * <code>optional uint32 distance = 1;</code>
       */
      public boolean hasDistance() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional uint32 distance = 1;</code>
       */
      public int getDistance() {
        return distance_;
      }
      /**
       * <code>optional uint32 distance = 1;</code>
       */
      public Builder setDistance(int value) {
        bitField0_ |= 0x00000001;
        distance_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 distance = 1;</code>
       */
      public Builder clearDistance() {
        bitField0_ = (bitField0_ & ~0x00000001);
        distance_ = 0;
        onChanged();
        return this;
      }

      private int time_ ;
      /**
       * <code>optional uint32 time = 2;</code>
       */
      public boolean hasTime() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional uint32 time = 2;</code>
       */
      public int getTime() {
        return time_;
      }
      /**
       * <code>optional uint32 time = 2;</code>
       */
      public Builder setTime(int value) {
        bitField0_ |= 0x00000002;
        time_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 time = 2;</code>
       */
      public Builder clearTime() {
        bitField0_ = (bitField0_ & ~0x00000002);
        time_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:HU.Nextturndistnaceevent)
    }

    // @@protoc_insertion_point(class_scope:HU.Nextturndistnaceevent)
    private static final gb.xxy.hr.NavStatServices.Nextturndistnaceevent DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new gb.xxy.hr.NavStatServices.Nextturndistnaceevent();
    }

    public static gb.xxy.hr.NavStatServices.Nextturndistnaceevent getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Nextturndistnaceevent>
        PARSER = new com.google.protobuf.AbstractParser<Nextturndistnaceevent>() {
      public Nextturndistnaceevent parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Nextturndistnaceevent(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Nextturndistnaceevent> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Nextturndistnaceevent> getParserForType() {
      return PARSER;
    }

    public gb.xxy.hr.NavStatServices.Nextturndistnaceevent getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_HU_NextTurnDetail_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_HU_NextTurnDetail_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_HU_Nextturndistnaceevent_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_HU_Nextturndistnaceevent_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020navigation.proto\022\002HU\"\207\004\n\016NextTurnDetai" +
      "l\022\014\n\004road\030\001 \001(\t\022%\n\004side\030\002 \001(\0162\027.HU.NextT" +
      "urnDetail.Side\022.\n\010nextturn\030\003 \001(\0162\034.HU.Ne" +
      "xtTurnDetail.NextEvent\022\021\n\tturngraph\030\004 \001(" +
      "\014\022\021\n\ttrunnumer\030\005 \001(\r\022\021\n\tturnangel\030\006 \001(\r\"" +
      ",\n\004Side\022\010\n\004LEFT\020\001\022\t\n\005RIGHT\020\002\022\017\n\013UNSPECIF" +
      "IED\020\003\"\250\002\n\tNextEvent\022\013\n\007UNKNOWN\020\000\022\013\n\007DEPA" +
      "RTE\020\001\022\017\n\013NAME_CHANGE\020\002\022\017\n\013SLIGHT_TURN\020\003\022" +
      "\010\n\004TURN\020\004\022\016\n\nSHARP_TURN\020\005\022\t\n\005UTURN\020\006\022\013\n\007" +
      "ONRAMPE\020\007\022\013\n\007OFFRAMP\020\010\022\t\n\005FORME\020\t\022\t\n\005MER",
      "GE\020\n\022\024\n\020ROUNDABOUT_ENTER\020\013\022\023\n\017ROUNDABOUT" +
      "_EXIT\020\014\022\035\n\031ROUNDABOUT_ENTER_AND_EXIT\020\r\022\r" +
      "\n\tSTRAIGHTE\020\016\022\016\n\nFERRY_BOAT\020\020\022\020\n\014FERRY_T" +
      "RAINE\020\021\022\017\n\013DESTINATION\020\022\"7\n\025Nextturndist" +
      "naceevent\022\020\n\010distance\030\001 \001(\r\022\014\n\004time\030\002 \001(" +
      "\r*O\n\006NavMes\022!\n\033MSG_TYPE_SENSORSTARTREQUE" +
      "ST\020\204\200\002\022\"\n\034MSG_TYPE_SENSORSTARTRESPONSE\020\205" +
      "\200\002B\034\n\tgb.xxy.hrB\017NavStatServices"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_HU_NextTurnDetail_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_HU_NextTurnDetail_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_HU_NextTurnDetail_descriptor,
        new java.lang.String[] { "Road", "Side", "Nextturn", "Turngraph", "Trunnumer", "Turnangel", });
    internal_static_HU_Nextturndistnaceevent_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_HU_Nextturndistnaceevent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_HU_Nextturndistnaceevent_descriptor,
        new java.lang.String[] { "Distance", "Time", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
